// IPC Channel names for communication between main and renderer processes
export const IPC_CHANNELS = {
  PROFILE: {
    LIST: 'profile:list',
    CREATE: 'profile:create',
    DELETE: 'profile:delete',
    SWITCH: 'profile:switch',
    GET_CURRENT: 'profile:get-current',
  },
  WORKSPACE: {
    LIST: 'workspace:list',
    CREATE: 'workspace:create',
    UPDATE: 'workspace:update',
    DELETE: 'workspace:delete',
    SWITCH: 'workspace:switch',
    GET_ACTIVE: 'workspace:get-active',
  },
  APP: {
    LIST: 'app:list',
    CREATE: 'app:create',
    UPDATE: 'app:update',
    DELETE: 'app:delete',
    HIBERNATE: 'app:hibernate',
    RESUME: 'app:resume',
    CREATE_INSTANCE: 'app:create-instance',
  },
  BROWSER_VIEW: {
    SHOW: 'browser-view:show',
    HIDE: 'browser-view:hide',
    UPDATE_BOUNDS: 'browser-view:update-bounds',
    NAVIGATE: 'browser-view:navigate',
    GO_BACK: 'browser-view:go-back',
    GO_FORWARD: 'browser-view:go-forward',
    RELOAD: 'browser-view:reload',
    FORCE_RELOAD: 'browser-view:force-reload',
    GET_STATE: 'browser-view:get-state',
    SET_ZOOM: 'browser-view:set-zoom',
    OPEN_DEVTOOLS: 'browser-view:open-devtools',
    CLOSE_DEVTOOLS: 'browser-view:close-devtools',
    TOGGLE_DEVTOOLS: 'browser-view:toggle-devtools',
    CLEAR_SESSION: 'browser-view:clear-session',
    GET_MEMORY: 'browser-view:get-memory',
    GET_CPU: 'browser-view:get-cpu',
    GET_ALL: 'browser-view:get-all',
  },
  WEBVIEW: {
    REGISTER: 'webview:register',
    UNREGISTER: 'webview:unregister',
    NAVIGATE: 'webview:navigate',
    GO_BACK: 'webview:go-back',
    GO_FORWARD: 'webview:go-forward',
    RELOAD: 'webview:reload',
    FORCE_RELOAD: 'webview:force-reload',
    GET_STATE: 'webview:get-state',
    SET_ZOOM: 'webview:set-zoom',
    OPEN_DEVTOOLS: 'webview:open-devtools',
    CLOSE_DEVTOOLS: 'webview:close-devtools',
    TOGGLE_DEVTOOLS: 'webview:toggle-devtools',
    CLEAR_SESSION: 'webview:clear-session',
    GET_MEMORY: 'webview:get-memory',
    GET_CPU: 'webview:get-cpu',
    GET_ALL: 'webview:get-all',
    UPDATE_ACTIVE: 'webview:update-active',
    INJECT_CSS: 'webview:inject-css',
    INJECT_JS: 'webview:inject-js',
    FIND_IN_PAGE: 'webview:find-in-page',
    STOP_FIND_IN_PAGE: 'webview:stop-find-in-page',
    PRINT: 'webview:print',
    SET_USER_AGENT: 'webview:set-user-agent',
    SET_AUDIO_MUTED: 'webview:set-audio-muted',
  },
  WINDOW: {
    TOGGLE_DEVTOOLS: 'window:toggle-devtools',
  },
  SETTINGS: {
    GET: 'settings:get',
    UPDATE: 'settings:update',
  },
  NOTIFICATION: {
    SHOW: 'notification:show',
    UPDATE_BADGE: 'notification:update-badge',
  },
} as const;

// Event names for main -> renderer communication
export const IPC_EVENTS = {
  WORKSPACE_CHANGED: 'workspace-changed',
  APP_UPDATED: 'app-updated',
  NOTIFICATION: 'notification',
  SHORTCUT_RELOAD: 'shortcut:reload',
  SHORTCUT_FORCE_RELOAD: 'shortcut:force-reload',
  SHORTCUT_TOGGLE_DEVTOOLS: 'shortcut:toggle-devtools',
  SHORTCUT_FIND: 'shortcut:find',
  SHORTCUT_PRINT: 'shortcut:print',
} as const;

// Default values
export const DEFAULTS = {
  DOCK_SIZE: 60,
  DOCK_POSITION: 'left' as const,
  IDLE_TIME_MINUTES: 15,
  THEME_MODE: 'system' as const,
  ACCENT_COLOR: '#667eea',
} as const;
